## Python libraries for data science
    . Numpy
    . Pandas
    . Matplot lib
    . Sciplot
    . Seaborn

In [2]:
## Numpy
import numpy as np
array_1d = np.array([1,2,3])
print(array_1d)
print(type(array_1d))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
li = [4,5,6,'z']
print(np.array(li))

['4' '5' '6' 'z']


In [14]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
a = np.random.randint(0,2,size = (2,2,2,2))
print(a)
print("shape :",a.shape) ## returns the length of the array
print("size :",a.size) ## return the size of the array
print("dtype :",a.dtype) ## return the type of the values in the array
print('itemsize :',a.itemsize)## return the size in bytes of each element in array 
print("dimen :",a.ndim)


[[[[1 1]
   [1 0]]

  [[0 1]
   [0 1]]]


 [[[1 0]
   [0 0]]

  [[0 1]
   [1 0]]]]
shape : (2, 2, 2, 2)
size : 16
dtype : int64
itemsize : 8
dimen : 4


In [28]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [31]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
b = np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
c=b+1
c

array([[2, 3, 4],
       [5, 6, 7]])

In [38]:
print(b+c)

[[ 3  5  7]
 [ 9 11 13]]


In [41]:
print(c/b)

[[2.         1.5        1.33333333]
 [1.25       1.2        1.16666667]]


In [42]:
print(b*c)

[[ 2  6 12]
 [20 30 42]]


In [43]:
print(np.sqrt(b))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [44]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [45]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [46]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])